pkg/ref/correlation.go

Add support for _Correlation_ labels in `refs`.  The goal is to provide a standard, shared implementation.  The functionality is a bit thin but I _think_ it adds value.
The application will be set in api package init().
```
func init() {
libref.Application = "virt.migration.openshift.io"
}
```
Example: Used when creating resources.
```
{
Labels: libref.CorrelationLabels(plan),
}
```

Add correlation labels.

---

pkg/ref/labels.go

Support for _correlation_ labels was added in the ref package because they are a form or reference.  The label is really a _reference label_ that is most commonly used for correlation.  It's important to name things for what they are and not what they're used for.  Since everything in Go is package-qualified, the _Correlation_ prefix should be removed.
Results (example) usage:
```
ref.Labels(plan)
```

correlation prefix removed.

---

pkg/ref/handler.go
pkg/ref/predicate.go
pkg/ref/ref_test.go

Add `Handler` to `refs` package.
Add support for mapping nested refs.  The refs are usually in `Spec`.

Add Handler and support nestd refs.

---

README.md
pkg/doc.go
pkg/error/error_test.go
pkg/error/wrap.go
pkg/inventory/container/container.go
pkg/inventory/container/doc.go
pkg/inventory/model/client.go
pkg/inventory/model/doc.go
pkg/inventory/model/model.go
pkg/inventory/model/model_test.go
pkg/inventory/model/table.go
pkg/inventory/web/doc.go
pkg/inventory/web/handler.go
pkg/inventory/web/web.go
pkg/logging/logger.go
pkg/logging/logger_test.go

Add `Error` and return _wrapped_ error instead of logging in all packages.
The inventory packages migration from MIG were logging error with log.Trace().  The initial thinking what that the _Logger_ for these packages could be set by the controller using them.  However, since the packages could be used in multiple contexts and goroutines, this isn't really a good idea.  To ensure that errors raised (created and returned) from the lib packages can be logged once with the original stack trace, this PR introduces _wrapping_.  Instead of a policy of trace-and-return, the policy will be wrap-and-return.  This introduces the unwanted complexities of error wrapping but I think it's worth it.  Mainly, that a type assertion or equality comparison is more complicated.  The wrapped error must be …

Add LibError and return wrapped error instead of logging.

---

pkg/inventory/model/model_test.go
pkg/ref/predicate.go
pkg/ref/ref_test.go

Support both `v1.ObjectReference` and `*v1.ObjectReference` fields.

Support ObjectReference by value in addition to pointer.

---

pkg/inventory/container/container.go
pkg/inventory/model/model_test.go
pkg/inventory/model/table.go

Two changes needed for virt.
1. Add `Reconciler.Owner()` so that the associated CR for the thing being reconciled is available.  In the case of virt, I need the `Provider`.
2. Add support for other integer types in the model.

Add reconciler owner; support all intX types in model.

---

pkg/inventory/container/container.go
pkg/inventory/container/doc.go
pkg/inventory/model/client.go
pkg/inventory/model/doc.go
pkg/inventory/model/journal.go
pkg/inventory/model/label.go
pkg/inventory/model/model.go
pkg/inventory/model/model_test.go
pkg/inventory/model/predicate.go
pkg/inventory/model/table.go

Model enhancements:
- Model watch event handler passed `Event` instead of `Model`.
- For _update_ events, the `Event.Updated` is populated.  This is needed so the handler can determine what changed (like controller-runtime predicates).
- The `Table` can generate the model _PK_ (primary key) field when not already set.  It is set as the sha256 of the _natural_ key fields.  This is currently implemented by each model but can be done by the `Table` since it has all the same information.  The `SetPk()` can be removed from the `Model` _interface_.
Unrelated:
- Renamed `Client.mutex` to `Client.dbMutex` for clarity.
- The `Journal.Client` field was removed.  The journal should never use the `Client` in which it is contained because it (the client)  is calling methods on the journal and has …

Model enhancements.

---

pkg/itinerary/doc.go
pkg/itinerary/simple.go
pkg/itinerary/simple_test.go

While working on the virt-controller, I noticed that I needed much of the same core _itinerary_ logic.  Seemed reasonable to factor this out into common.
See the unit test for example/usage.

Add itinerary

---

pkg/inventory/container/ocp/collection.go
pkg/inventory/container/ocp/reconciler.go

Both MTC (discovery) and MTV (provider) inventory controllers need to inventory kubernetes resources on the destination.  This mostly grabbed from the discovery service.

Add OCP data reconciler.

---

pkg/inventory/container/container.go
pkg/inventory/container/ocp/collection.go
pkg/inventory/container/ocp/reconciler.go

Adds the Container.Replace() method to be more explicit.  It's important to support the replace within the container instead of the application (caller) doing a Delete() & Add() because the mutex prevents race conditions. 
Also, removed the `purge` parameter from Reconciler.Shutdown() because it was not being used and more appropriate (and symmetrical) to have the application (caller) completely mange the lifecycle of the DB.

Add inventory Container.Replace().

---

pkg/inventory/container/container.go
pkg/inventory/container/ocp/doc.go
pkg/inventory/container/ocp/reconciler.go

Some OCP (data) reconciler improvements:
- use the regular cached client.  This eliminates a double connect.
- asynchronous Start().
- Shutdown() idempotent.

Use cached client in OCP reconciler.

---

pkg/inventory/model/predicate.go
pkg/inventory/model/table.go
pkg/itinerary/simple.go

Errors must only be wrapped in context to capture the correct stack trace.

Errors must only be wrapped in context.

---

pkg/condition/condition.go
pkg/inventory/container/ocp/reconciler.go

Add convenience method for aggregating conditions.
Also, go back to using non-cached client in the OCP reconciler.  I have observed race conditions when listing resources and when the cache is updated by watch.

Add Conditions.UpdateConditions()

---

pkg/itinerary/simple.go
pkg/itinerary/simple_test.go

Use int64 in `Progress` object to accommodate broader use cases such as memory and storage capacity.

Use int64 in progress object.

---

pkg/inventory/web/web.go

This pull request enable TLS for the inventory container if the configuration provides TLS configuration.
The certificate and key are provided by a secret automatically generated by the openshift-service-serving-signer, so the CA certificate chain is mounted in every pod as `/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt`. The secret is mounted in a path based on the secret name.
More information on using service serving certificates is available at [OpenShift > Security and compliance > Configuring certificates > Securing service traffic using service serving certificate secrets](https://docs.openshift.com/container-platform/4.6/security/certificates/service-serving-certificate.html).
The deployment, service and route are modified in …

Enable TLS for inventory

---

pkg/inventory/model/client.go
pkg/inventory/model/model_test.go

Two main changes:
The `Client`had 2 mutexes: (1) to protect the internal state of the `Client` and another (2) for the DB write lock. Even after extensive concurrency testing, I discovered a deadlock scenario whereby the two mutexes are acquired in opposite order.  This is always a danger when acquiring more than 1 mutex at a time.  This is safe so long as they are always acquired in the same order but the transaction flow introduces situations that breaks this rule.  The goal of the 2 mutexes was to keep all of the functionality in the `Client` (even transactions).  In hind sight, not worthwhile.
The solution is to reduce the needed mutexes to 1.  This can be accomplished with a cleaner separating of the `Client` and `Tx` (transaction) objects.  This is a traditional design anyway.  
--- …

Model improvements 4.

---

pkg/inventory/container/ocp/reconciler.go

Update the OCP (data) reconciler to use the transaction for insert, update, and delete else blocks-forever (deadlock).
fixes #38

Fix ocp (data) reconciler using transactions.

---

pkg/inventory/container/ocp/reconciler.go

Disable metrics on remote manager in OCP (data) reconciler to avoid port 8080 already in use error.
https://book-v1.book.kubebuilder.io/beyond_basics/controller_metrics.html
_Please note that metrics support has been added in controller-runtime 0.1.8+ release which is the default version for Kubebuilder 1.0.6+ releases. So if your project was created using 1.0.5 or older kubebuilder, then update the controller-runtime dependencies to 0.1.8 or higher._
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/manager/manager.go#L127

Disable metrics on remote manager in OCP (data) reconciler.

---

go.mod
pkg/error/error_test.go
pkg/error/wrap.go

Supported nested `Unwrap()`.
Needed for cases where an `Error` is created using `Wrap()` and passed an error (of another type) that is already wrapped.

Error support nested unwrap.

---

pkg/inventory/model/client.go
pkg/inventory/model/journal.go
pkg/inventory/model/model.go
pkg/inventory/model/model_test.go

Model journal improvements.
- **Removed concept of enabling/disabling the journal.**  Instead, the journal only records (stages) events when there is at least (1) watch for the model (kind).
- **Reduce the risk of initial `Created` events from exceeding the queue (channel) limit.**  This is accomplished by passing the list of existing models to the watch on `Start()` instead of writing them to the queue.  Subsequent (change) events should not exceed the queue limit.  However, in the unlikely event they do, the watch is notified using the `Watch.Error()` and the watch should be restarted.

Model: Journal improvements

---

pkg/inventory/model/model_test.go
pkg/inventory/model/predicate.go

Support List predicates values of type `Field`.
This is needed so support listing models by selected by comparing 2 fields on the (same) model.
Example:
```
type Person struct {
CityBorn string `sql:""`
City     string `sql:""`
}
```
To select people living in "Huntsville".
```
Eq("City", "Huntsville")
```
To select people not living in the city where they were born.
```
Neq("City", Field{Name: "CityBorn"})
```

Support predicate field values.

---

pkg/inventory/model/journal.go
pkg/inventory/model/model_test.go

Add support for the watch event handler to be notified when a watch has Started().  This provides the event handler an opportunity to do construction & initialization.
Add _stub_ watch event handler.  Support event handler only implementing methods for events it cares about.

Add event handler started().

---

pkg/inventory/container/ocp/reconciler.go
pkg/inventory/model/client.go
pkg/inventory/model/predicate.go
pkg/inventory/model/table.go

The original philosophy was the by wrapping errors at all levels would:
- Ensure errors got wrapped.
- Easier to code review because it's consistent.
After living with it for a while it seem apparent that neither are true.  Wrapping only where errors are returned by external packages is:
- reliable
- straight forward to code review
- reduces code noise.

Wrap errors only at the edge.

---

go.mod
go.sum
pkg/inventory/model/client.go
pkg/inventory/model/journal.go
pkg/inventory/model/model_test.go
pkg/inventory/web/client.go
pkg/inventory/web/handler.go

Add support for watch in web layer.
This includes tools for the web (endpoint) _handler_.
Extensions to the web client.
Model <- (model)watch <- endpoint <- (resource)watch  [websocket] <- client
---
Loosely related:
Adds _Parity()_ event to the model event handler.
Adds Watch.End() for ending a watch for symmetry with web layer `Watch`.
Adds _Get()_ and _Post()_ to _base_ client.  Reduces code duplication in concrete clients.

Add support for watch in web layer.

---

pkg/error/doc.go
pkg/error/error_test.go
pkg/error/wrap.go
pkg/logging/logger.go
pkg/logging/logger_test.go

Add support for user provided context in error.Wrap().
Update the `logging` package to incorporate the context when logging.  Logger.Error() will append `Error.Context()` key/value pairs to those included in the call.

Add support for user provided context in error.Wrap().

---

pkg/inventory/model/client.go
pkg/inventory/model/model_test.go

The _initial_ listing needs to have detail level (1) to include all fields.

Fix detail=1 in initial CREATED watch listing.

---

pkg/inventory/web/client.go
pkg/inventory/web/handler.go

Fix building watch header.  Header needs to be composed of the X-Watch header and existing headers (like the _Authorization_ header).
`Authorized` handler base removed.  No longer used.

Web authorization updates.

---

pkg/logging/logger.go
pkg/logging/logger_test.go

Primarily adds support for:
- Wrapping any `Real` log.Logger implementation using _factory_ pattern.
- Using any name generator using _factory_ pattern.
- Logger with _plain_ name (without reconcile suffix).

Logger support plan named; Support logger and name generator factory.

---

go.mod
pkg/filebacked/catalog.go
pkg/filebacked/doc.go
pkg/filebacked/file.go
pkg/filebacked/iterator.go
pkg/filebacked/list.go
pkg/filebacked/list_test.go
pkg/inventory/model/client.go
pkg/inventory/model/journal.go
pkg/inventory/model/model_test.go
pkg/inventory/model/table.go
pkg/inventory/web/handler.go
pkg/logging/logger.go
pkg/logging/logger_test.go

Add `filebacked` package which provides file-backed collections.
The goal is to: Reduce memory footprint for flows that require holding (potentially) large collections of objects.
The design is to: briefly cache the collections on disk.
Known use cases in the `inventory` package:
- The journal needs to _stage_ change events during transactions.
- The journal needs to queue (potentially) large number of `Event` to watch handlers WITHOUT blocking DB updates or holding the DB lock.
- The web package needs to be able to `List()` (potentially) large numbers of objects to be streamed back WITHOUT holding the DB lock.
This is most necessary for the journal/watch because it is a producer/consumer workflow with no guarantee the consumer can keep up with the producer.
---
Unrelated:  Noticed the …

File-based collections.

---

README.md
go.mod
pkg/filebacked/file.go
pkg/inventory/container/container.go
pkg/inventory/container/ocp/reconciler.go
pkg/inventory/model/client.go
pkg/inventory/model/doc.go
pkg/inventory/model/journal.go
pkg/inventory/model/model.go
pkg/inventory/model/model_test.go
pkg/inventory/model/table.go
pkg/inventory/web/client.go
pkg/inventory/web/handler.go
pkg/inventory/web/web.go
pkg/logging/factory.go
pkg/logging/logger.go
pkg/logging/logger_test.go
pkg/ref/handler.go
pkg/ref/mapping.go
pkg/ref/predicate.go
pkg/ref/ref.go
pkg/ref/ref_test.go

Add logger to many objects.
Strategic add of logging statements.
Add context to wrapped/returned `error`.
The log level approach:
- Level=**0-2** not used by the lib.  reserved for applications.
- Level=**3** for: basic `info` logging for high level things created/deleted opened/closed.
- Level=**4** for: basic `debug`.  has a lot of detail but relatively low numbers
- Level=**5** for: low level `debug`.  high volume changes like watch events and _filebacked_ read/write.
Added an `id` to both `model.Watch` and both `model.Event` and `web.Event` for better tracability.
change some function calls where the return is deliberately ignored (for clarity) to:
```
_ = fn()
```
Fixed a bug in the `ref` package for _references watches_.  The handler needed to filter for by reference _owner_ type. …

Better logging

---

pkg/inventory/web/client.go

Propagate the watch ID through to the client watch handler for improved traceability.

Web: propagate watch id to client handler.

---

pkg/filebacked/list.go
pkg/filebacked/list_test.go
pkg/inventory/model/client.go
pkg/inventory/model/journal.go
pkg/inventory/model/model_test.go
pkg/inventory/model/table.go
pkg/inventory/web/handler.go

Fix watch leaked when:
- There is an error after the watch is created but before it is successfully returned.
- A _web_ layer watch terminates.  The watch <=> handler (circular) relationship will prevent GC.
Also, adding `NewList()` which creates a list with a  _finalizer_  set.  The `Iterator` already` has a finalizer.  This is more consistent, intuitive and safer.

Fix watch leak.

---

pkg/inventory/model/client.go
pkg/inventory/model/doc.go
pkg/inventory/model/model_test.go
pkg/inventory/model/table.go

Add index() field tag.  This will create a non-unique index for fields in the _group_.
Example:
```
type Person struct {
Name string `sql:"index(a)"`
}
```
---
Add DB.Execute(sql string) to support running arbitrary SQL needed to support editing table data outside of the _Model_.

Add index() field tag.

---

pkg/inventory/web/client.go

Read and close the body regardless of http code.  This seems to be best practice to prevent memory leaks.

Http client body read and closed.

---

pkg/inventory/web/client.go

Add support for _optional_ list of query params in web client.Get().

Add support for query params in web client.Get().

---

pkg/inventory/model/table.go

Augment `Table` to Include _params_ when wrapping errors.  Without this, the _sql_ information is less valuable.

Add params to table error context.

---

Makefile
pkg/cmd/doc.go
pkg/cmd/inventory/main.go
pkg/inventory/model/client.go
pkg/inventory/model/doc.go
pkg/inventory/model/model_test.go
pkg/inventory/web/client.go
pkg/inventory/web/handler.go
pkg/logging/factory.go

General hardening.
Fix leaked `Watch` terminated when DB closed.
Fixed leaked `WatchWriter` when peer closes connection or connection broken.
Fixed _database locked_ error when transaction is committed when another goroutine is iterating a DB cursor (Rows).
Added finalizers for additional leak protection.
Updated logger factory to not add the `Sampler` for non-development logger.  This used a ton of memory and I don't think it's worth the cost.
Added _integration_ test for the web/model stack.

General hardening and leak fixes for model and web packages.

---

pkg/inventory/model/model_test.go
pkg/inventory/model/table.go

Adjust (simplify) _model_ layer detail levels.
Level=1 no longer indicates all.
Default levels are 0 for keys and 1 for all other fields unless specified.

Adjust model detail levels.

---

pkg/inventory/model/label.go
pkg/inventory/model/model_test.go
pkg/inventory/model/table.go

Better derived PK.  Modeler more explicitly defines if/how PK is derived.
Currently the PK is derived using the _natural_ key fields any time the field is blank which can result in operations on models using a non-deterministic PK.  And/or report errors when the PK is black as the generated (incorrect) key.

Better generated PK.

---

pkg/inventory/container/collection.go
pkg/inventory/container/collection_test.go
pkg/inventory/container/ocp/reconciler.go
pkg/inventory/model/client.go
pkg/inventory/model/journal.go
pkg/inventory/model/model.go
pkg/inventory/model/model_test.go
pkg/inventory/model/table.go

Add the `Collection` to the _container_ package.
Provides reconciliation of a collection of stored models based on a collection of desired models.
Add the `sql:"incremented"` tag for _auto-incremented_ fields.
Relaxed the `Model` interface.  Equals(), Labels() and String() no longer required.  The Labels() and String() are now optional.

Add container.Collection.

---

pkg/filebacked/file.go
pkg/filebacked/iterator.go
pkg/filebacked/list.go
pkg/filebacked/list_test.go
pkg/inventory/container/collection.go
pkg/inventory/container/collection_test.go
pkg/inventory/model/journal.go
pkg/inventory/model/model_test.go
pkg/inventory/model/table.go

The filebacked object methods no longer return error but panic instead.
The root cause of I/O and serialization errors are not situational or recoverable.
Also add Event.append() and Event.next() to encapsulate the _protocol_ for writing/reading event from the filebacked list.

Simpler filebacked API; no longer return error.

---

pkg/inventory/model/model_test.go
pkg/inventory/model/table.go

Reflect auto-incremented fields in created/updated model.  This is mainly needed so that models delivered by the watch (system) will accurately reflect the value.
Also, added a unit test for auto-incremented fields.

Reflect auto-incremented fields in created/updated model.

---

pkg/filebacked/file.go
pkg/filebacked/iterator.go
pkg/filebacked/list.go
pkg/filebacked/list_test.go
pkg/inventory/container/collection.go

Add direct-indexed access to the `filebacked.Iterator`.
List example:
```
for i := 0; i < list.Len(); i++ {
object := list.At(i)
}
```
```
for i := 0; i < list.Len(); i++ {
object := <thing>
list.AtWith(i, &object))
}
```
Iterator example:
```
itr := list.Iter()
for i := 0; i < itr.Len(); i++ {
object := itr.At(i)
}
```
```
itr := list.Iter()
for i := 0; i < itr.Len(); i++ {
object := <thing>
itr.AtWith(i, &object))
}
```
The filebacked API reorganized to promote direct access in favor of Next() and NextWith().
The open() on both `Reader` and `Writer` could be simplified to panic instead of return error.
The `Reader` could be simplified to only support At() and AtWith().
Introduced the concept of a _shared_ reader to efficiently support At() and AtWith() read operations on `List`.
The …

Direct indexing

---

pkg/inventory/model/client.go
pkg/inventory/model/doc.go
pkg/inventory/model/journal.go
pkg/inventory/model/model.go
pkg/inventory/model/model_test.go
pkg/inventory/model/session.go

Improved model concurrency by using the `sqlite3` [WAL](https://sqlite.org/wal.html) journal.
The WAL journal supports concurrent read/write among separate DB connections.  As a result, the MUTEX used by the `model.Client` is no longer needed.  Instead, the `Client` sets the WAL pragma and maintains a _pool_ of DB `Session` which encapsulates a actual DB connection and provides DB connection reservation.  The pool dedicates a percentage to writing vs reading to prevent starvation of either operation.
The `model.Journal` no longer maintains the list of _staged_ events.  Its interface has slimmed down accordingly.
Instead, each transaction (Tx) contains the list of staged events which are reported (to the journal) in `Tx.Commit()`.
The unit tests file names needed to be unique to eliminate …

Improved model concurrency.

---

pkg/filebacked/file.go
pkg/inventory/container/collection_test.go
pkg/inventory/model/client.go
pkg/inventory/model/doc.go
pkg/inventory/model/model_test.go
pkg/inventory/model/table.go

Add support for `sql:"-"` to omit fields.
The `sql:""` tag is optional.  All fields will be included by default unless omitted.  Fields of type _struct_ will be aggregated unless an explicitly tagged.
Renamed Client.Iter() and Table.Iter() to Find().  Better to be a verb and more consistent with other methods.
Added unit tests.
Ensure all unit tests use their own DB.

Minor Model Enhancements

---

README.md
pkg/inventory/model/client.go
pkg/inventory/model/journal.go

insert,update,delete moved to level=3.
This violates the guideline that level 4+ is when high-volume things are logged but seems useful to log when models are written at the lower level without all of the noise at level 4.

Adjust model logging. 

---

pkg/inventory/model/client.go
pkg/inventory/model/journal.go
pkg/inventory/model/model_test.go
pkg/inventory/web/handler.go

Add support for associating labels with transactions.
Transaction labels are passed through on watch `Event`.
The goal is to provide a method for handlers to ignore events based on labels.  A primary use case is an event handler that updates the model and needs to ignore the associated update _(echo)_ event.

Transaction labels passed through on watch event.

---

go.mod
go.sum

Upgrade to gin 1.7.2 for CVE-2020-28483.
---
CVE-2020-28483
high severity
Vulnerable versions: < 1.7.0
Patched version: 1.7.0
This affects all versions of package github.com/gin-gonic/gin under 1.7.0. When gin is exposed directly to the internet, a client's IP can be spoofed by setting the X-Forwarded-For header.

Upgrade to gin 1.7.2 re: CVE-2020-28483.

---

pkg/filebacked/iterator.go
pkg/filebacked/list.go
pkg/filebacked/list_test.go
pkg/inventory/container/collection.go
pkg/inventory/model/client.go
pkg/inventory/model/doc.go
pkg/inventory/model/field.go
pkg/inventory/model/inspect.go
pkg/inventory/model/model_test.go
pkg/inventory/model/relation.go
pkg/inventory/model/table.go

Better support cascade delete based on foreign keys.
This needs to be done by the model layer instead of in the DB using _ON CASCADE DELETE_ foreign key constraints to support event generation.
This PR:
- Refactor `Table` object and split out the model _inspection_ functionality (which includes `Field`) into a _new_ model `Definition` object.
- Add _new_ `DataModel` which is the collective representation of all models.
- Add _new_ `FkRelation` object to model foreign key relationships and provide functionality needed to support cascade delete based on FK relationships. Find dependent models.
- Enhanced FK tag: `fk(`_table_, _+must +cascade_`)` makes enforcement (with constraint) and cascade delete optional.
- Update _filebacked_ package
- Update List.Append() to append `Iterator`.
- Add …

Cascading Delete.

---

pkg/inventory/model/field.go
pkg/inventory/model/model_test.go

After working with this for a bit, It seems more intuitive for the model layer is to select/populate **all** fields by default.  I think only selecting/populating the _key_ fields would be unexpected.
Applications using the _lib_ should add adjust as needed:
```
func init() {
libmodel.DefaultDetail = 3
}
```
when working with _custom_ detail levels.

model.DefaultDetail should be 0.

---

pkg/inventory/model/client.go
pkg/inventory/model/model_test.go
pkg/inventory/model/predicate.go
pkg/inventory/model/table.go

Add support for update with (optional) predicate.  The predicate is in addition to the PK match.
Eg:
`db.Update(model, Eq("Revision", 1))`

Support update predicate.
