konveyor/controller

- pkg/inventory/model/client.go
- pkg/inventory/model/model_test.go
- pkg/inventory/model/table.go
Moved the responsibility for CRUD of  Model `labels` to the Client.  This ensures clean separation of concerns and layering.  
The `Table` is concerned with operations on `interface{}` and DB tables.
The `Client` is concerned with operations on `Model`.
Renamed `Table.Db` to `Table.DB` for consistency with other packages.
Added minimum label unit test.
> Label management concern of the client.

- pkg/inventory/web/handler.go
Initial support for k8s (SAR) authorization.
> Add Authorized handler.

- pkg/condition/condition.go
- pkg/condition/condition_test.go
Serialize the Condition.Items list instead of substituting "[]" to/from Condition.Message.
> Condition.Items serialized instead of substituted in the message.

- pkg/inventory/model/client.go
- pkg/inventory/model/model_test.go
- pkg/inventory/model/table.go
Fix DB.Count().
Needed to:
- add Count() to the interface.
- ListOptions.Count needed to be removed since passing ListOptions.Count=true to DB.List() would not have the expected result.
> Fix count.

- pkg/itinerary/simple.go
- pkg/itinerary/simple_test.go
Added `Itinerary.Progress()` needed by CAM.
Added `Itinerary.List()`.  List of steps filtered by predicates used by multiple other methods.
Added `Itinerary.First()`. Originally used in unit tests and seemed generally useful.
Renamed: `Predicate.Allowed()` ==> `Predicate.Evaluate()`.  Seemed more appropriate.
Added unit tests.
> add progress report to itinerary.

- pkg/condition/condition.go
Update `SetCondition()` to add/update multiple conditions.
Removed `SetReady()` and `SetReconcileFailed() because they do not add sufficient value.
> Minor conditions updates.

- pkg/inventory/web/web.go
Add port setting to web server.
> Add port setting to web server.

- pkg/inventory/model/client.go
Disable the journal when DB closed.
Add DB.EndWatch().
> Disable the journal when DB closed; add DB.EndWatch().

- pkg/condition/condition.go
- pkg/inventory/container/container.go
Update _Reconciler_ interface: add `Test()`.
> Add Reconciler.Test().

- pkg/inventory/model/predicate.go
> Predicate match ignore case.

- pkg/condition/condition.go
Support serializing un-initialized (nil) `Conditions.List`.
> Support empty conditions.

- pkg/inventory/container/container.go
- pkg/inventory/container/ocp/reconciler.go
Implement OCP data reconciler Test().
> Implement OCP data reconciler Test().

- pkg/inventory/container/container.go
- pkg/inventory/container/ocp/reconciler.go
- pkg/inventory/web/handler.go
Replaced terminology: consistency with parity.
> Replaced consistency with parity.

- pkg/inventory/container/container.go
- pkg/inventory/web/web.go
> Container keyed by UID.

- pkg/inventory/container/container.go
- pkg/inventory/model/client.go
- pkg/inventory/model/journal.go
- pkg/inventory/model/model_test.go
- pkg/inventory/web/client.go
- pkg/inventory/web/handler.go
Watch fixes and enhancements found while testing.
Model:
Add `Journal.Close()` and called by `DB.Close()`.  This will terminate all of the watches.
Web:
Improved watch life-cycle support.
> Inventory: watch fixes and enhancements.

- pkg/error/error_test.go
- pkg/error/wrap.go
Support context keywords in error.New().
> Support context keywords in error.New().

- pkg/inventory/web/client.go
Propagate TLS configuration to _websocket_ dialer.
> Propagate TLS configuration to websocket dialer.

- README.md
- pkg/filebacked/file.go
- pkg/inventory/model/client.go
- pkg/inventory/model/doc.go
- pkg/inventory/model/model.go
- pkg/inventory/model/table.go
- pkg/logging/factory.go
Logging adjustments.
All `filebacked` logged at level=5.
Fix debugging logger DEBUG instead of WARN.
More detail in model.Client and model.Table.
> Logging adjustments.

- pkg/cmd/inventory/main.go
- pkg/inventory/model/client.go
- pkg/inventory/model/journal.go
- pkg/inventory/model/model_test.go
- pkg/inventory/web/client.go
- pkg/inventory/web/handler.go
Add support for watch options.
- **snapshot** _(bool)_ - List models in the collection and report as `Created` events for each before reporting `Parity`.
Making the snapshot optional will eliminate thousands of unnecessary watch events for handlers that don't want the snapshot.
Snapshot (list of models) explicitly passed to Watch.Start() instead of the watch assuming the first iterator in the queue is the snapshot.
Grab the read lock on the DB at in Client.Watch().  This ensures no other client methods can queue events _before_ the snapshot.
> Add watch options.

- pkg/inventory/web/client.go
Commit meant to be included in https://github.com/konveyor/controller/pull/77
Don't overwrite request header.
Const for snapshot option.
> Don't overwrite request header.

- README.md
- pkg/filebacked/file.go
- pkg/inventory/model/client.go
Updating logging.
- adjusted I/O logging levels in `filebacked`.
- added `duration` to model.Client CRUD methods logging.
- added "lifespan" to transactions logging.
> Updating logging.

- pkg/cmd/inventory/main.go
- pkg/inventory/container/container.go
- pkg/inventory/container/doc.go
- pkg/inventory/container/ocp/collection.go
- pkg/inventory/container/ocp/collector.go
- pkg/inventory/web/handler.go
Reconciler renamed: Collector.  The name _Reconciler_ has strong ties to OpenShift controllers.
> Reconciler renamed: Collector.

- pkg/inventory/model/client.go
- pkg/inventory/model/model_test.go
Fix Event.Updated and Event.Model reversed after journal=WAL added.
Added additional unit tests.
> Fix Event.Updated and Event.Model reversed after journal=WAL added.

- pkg/cmd/inventory/main.go
- pkg/inventory/model/client.go
- pkg/inventory/model/doc.go
- pkg/inventory/model/model_test.go
- pkg/inventory/model/table.go
Default field detail = _DefaultDetail_(9) which equals _MaxDetail_ (by default).
This will better support user building (mid level) details levels.
> Model detail enhancements.
